# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Upload artifact to Firebase Distribution
        uses: ./
        with:
          appId: ${{secrets.FIREBASE_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: hellfire-club
          file: ApiDemos-debug.apk
